version: "3.9"
services:
  app:
    build: .
    env_file: .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - API_KEY=${API_KEY}
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    ports:
      - "8000:8000"
    depends_on:
      - mlflow
    volumes:
      - ./:/app
      - ./vectorstore:/app/vectorstore

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.16.0
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri /mlflow --default-artifact-root /mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./_mlflow:/mlflow
